### ISSUE TITLE
Error with `MyQuan` Class at Quantization Level Below 512

### ISSUE THREAD

**Issue by LumenScopeAI** [Intelligent-Computing-Research-Group/SpikeZIP-TF#2]
#### Description

I am experiencing an error when using the `MyQuan` class from this repository for quantization. The specific error message states that the "probability tensor contains either `inf`, `nan` or element < 0," which occurs when the `quantization_level` is set below 512.

#### Steps to Reproduce

1. Initialize the `MyQuan` class with `quantization_level` set to a value less than 512.
2. Process a standard input tensor through the class.
3. The error appears during the computation, indicating issues with the generated probability tensor.

**Comment by xianyi11** [comment]
Thanks for your interest in our work.  Our myquan function is based on the paper: Learned Step Size Quantization (LSQ). The implementation of  LSQ can also be seen in github repo: https://github.com/zhutmost/lsq-net. Can you provide the detail code file and input file such as .pth or .npy files below for better reproduction?
