### ISSUE TITLE
疑似涉及学术不端

### ISSUE THREAD

**Issue by LumenScopeAI** [Intelligent-Computing-Research-Group/SpikeZIP-TF#4]
你们的Spike-ZIP ANN2SNN”无损转化“算法，我提出以下疑问：

- 你们的QAT方法理论层面可行，然而对LLaMA2、LLaMA3、Qwen2等LLM预训练权重直接使用paper所述的QAT方法，在前向传播时会出现nan/inf，在反向传播时会出现梯度消失，因此Spike-ZIP所述的针对LLM预训练权重进行QAT并ANN2SNN，在第一步QAT就不可行了，没有考虑预训练权重初始化条件是否会在量化中引入异常值的问题，请问你们团队是否有进行相关实验确保Paper的严谨与正确？
- Spike-ZIP提出了一种神经元替代量化器的方法进行QAT后的QANN2SNN的转化，paper所述算法未考虑计算结果离群值造成的影响，下图为离群值范围与误差分析的结果示意图（使用的是此仓库开源的代码），此量级的误差，经实验验证，会使得LLM完全丧失语言能力。

综上，我希望Spike-ZIP团队能够提供视觉Transformer模型以外的实验结果来确保自己的算法是可行的。

![489cd54089e2b4dae26fdb9ada8cd65](https://github.com/user-attachments/assets/c551cd6d-3ba2-4efc-99d8-442983ef8785)

**Comment by elliothe** [comment]
学者你好，不知道为何会采取学术不端的词语来抨击我们的工作。关于你的疑问我的回复如下：

该开源工作是我们ICML2024的论文内的内容。在文章中，我们没有做出任何声明我们现在的工作能原封不动的支持大模型SNN化。当前大模型量化的outlier本身就是一个研究热点，需要开展更多的工作才能实现大模型的SNN化。

我们也会积极的对我们的工作进行延展，从而更好的支持现有的人工智能、大模型生态。

但你对我们的工作采用 “学术不端”的指责我们是不接受的。

**Comment by LumenScopeAI** [comment]
> 学者你好，不知道为何会采取学术不端的词语来抨击我们的工作。关于你的疑问我的回复如下：
> 
> 该开源工作是我们ICML2024的论文内的内容。在文章中，我们没有做出任何声明我们现在的工作能原封不动的支持大模型SNN化。当前大模型量化的outlier本身就是一个研究热点，需要开展更多的工作才能实现大模型的SNN化。
> 
> 我们也会积极的对我们的工作进行延展，从而更好的支持现有的人工智能、大模型生态。
> 
> 但你对我们的工作采用 “学术不端”的指责我们是不接受的。

因为你们在论文中指出，在插入量化器之后，需要对模型进行微调来维持一定的性能，之后再进行QANN到SNN的转化，而事实上经过实验，插入量化器之后会导致模型出现如题所述的问题，唯一的解决方式是在插入亮化期之后进行重新预训练，这样才能够满足论文所述算法的最基本前提，然而预训练与微调的代价相差甚大，因此我认为论文过于“春秋笔法”。

**Comment by LumenScopeAI** [comment]
> 学者你好，不知道为何会采取学术不端的词语来抨击我们的工作。关于你的疑问我的回复如下：
> 
> 该开源工作是我们ICML2024的论文内的内容。在文章中，我们没有做出任何声明我们现在的工作能原封不动的支持大模型SNN化。当前大模型量化的outlier本身就是一个研究热点，需要开展更多的工作才能实现大模型的SNN化。
> 
> 我们也会积极的对我们的工作进行延展，从而更好的支持现有的人工智能、大模型生态。
> 
> 但你对我们的工作采用 “学术不端”的指责我们是不接受的。

同时，论文有提到用本文所提出的神经元方程，替代量化器即可实现ANN到SNN的转化，然而我在使用此项目提供的代码进行测试的时候，发现这两者并不能等价，并且其中的误差足以使一个大语言模型完全失去“语言能力“（我认为已经失去语言能力就没必要使用PPL等指标佐证了），因此我认为，你们的神经元方程是有问题的，仅理论上可行，然而模型前向传播时产生的离群值会使得论文所述的算法完全失效。

**Comment by LumenScopeAI** [comment]
> 学者你好，不知道为何会采取学术不端的词语来抨击我们的工作。关于你的疑问我的回复如下：
> 
> 该开源工作是我们ICML2024的论文内的内容。在文章中，我们没有做出任何声明我们现在的工作能原封不动的支持大模型SNN化。当前大模型量化的outlier本身就是一个研究热点，需要开展更多的工作才能实现大模型的SNN化。
> 
> 我们也会积极的对我们的工作进行延展，从而更好的支持现有的人工智能、大模型生态。
> 
> 但你对我们的工作采用 “学术不端”的指责我们是不接受的。

直接采取”学术不端“这个词我感到诚挚的道歉，因为之前我采用”算法疑问“作为标题没能得到回复，因此希望用更为”激进“的标题取得与你们的沟通。
不过我希望你们能为上述两个质疑给出一定的回复。
