### ISSUE TITLE
NLP task code missing.

### ISSUE THREAD

**Issue by bollossom** [Intelligent-Computing-Research-Group/SpikeZIP-TF#5]
How nice work SpikeZIP-TF is!!!

However, I would like to inquire about the specific settings and code used for the NLP tasks. 
When attempting to replicate the results using the code from the SpikeBERT repository, I found that with 125M parameters and t=64, Spikezip achieved an accuracy of only 88.7 on the SST-2 task, which is significantly lower than the 92.81 reported in the table.

I would greatly appreciate it if you could spare some time to address this issue. Thank you for your attention, and I look forward to your response.

**Comment by xianyi11** [comment]
Thanks for your interest in SpikeZIP-TF!!! Now you can access the NLP task code by switching the main branch to the NLU task branch!! You can reproduce the results in paper by running the codes.

**Comment by bollossom** [comment]
Thanks a lot.
