### ISSUE TITLE
Questions on different training stages

### ISSUE THREAD

**Issue by JeffreyWong20** [Intelligent-Computing-Research-Group/SpikeZIP-TF#6]
Hi, thank you for the amazing work.

If I understand the paper correctly, there are two training stages, one for fine-tuning ViT-S-ReLU on ImageNet and the other for fine-tuning ViT-S-ReLU-Quantized on ImageNet.

Could you kindly provide an example for the first training stage instead of just the checkpoints? It is unclear to me whether both fine-tuning utilised knowledge distillation. I tried referring to the paper, but it provides limited detail regarding how the fine-tuning was actually done.

I would also appreciate it if the code for NLP could be provided so we can reproduce the results stated in the paper. 

Thank you!

**Comment by xianyi11** [comment]
Thanks for your interest in SpikeZIP-TF!!!! The NLP code is access now in the NLU_tasks branch. The repo can also training relu-based ANN by following commands:
```
cd /home/zekai_xu/SNN/code/SpikeZIP_transformer
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port='29500' main_finetune.py \
    --accum_iter 4 \
    --batch_size 192 \
    --model vit_small_patch16 \
    --model_teacher vit_small_patch16 \
    --finetune vit_small_patch16_224.augreg_in21k_ft_in1k.bin \
    --pretrain_teacher vit_small_patch16_224.augreg_in21k_ft_in1k.bin \
    --epochs 100 \
    --blr 1e-4 --layer_decay 0.65 \
    --weight_decay 0.05 --drop_path 0.1 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path /ImageNet/ --output_dir output_dir/ --log_dir output_dir/ \
    --mode "ANN" --act_layer relu --act_layer_teacher gelu --temp 2.0 --wandb --print_freq 200 --define_params --mean 0.5 0.5 0.5 --std 0.5 0.5 0.5 
```
We also use distillation in the first stage. Looking forward to further discussion!!!

**Comment by JeffreyWong20** [comment]
Thank you!
